/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_obstacle_free: (a: number, b: number) => void;
export const __wbg_get_obstacle_x: (a: number) => number;
export const __wbg_set_obstacle_x: (a: number, b: number) => void;
export const __wbg_get_obstacle_base_speed: (a: number) => number;
export const __wbg_set_obstacle_base_speed: (a: number, b: number) => void;
export const __wbg_world_free: (a: number, b: number) => void;
export const world_new: (a: number) => number;
export const world_update: (a: number, b: number) => void;
export const world_get_best_dino_x: (a: number) => number;
export const world_get_best_dino_y: (a: number) => number;
export const world_get_best_dino_velocity_y: (a: number) => number;
export const world_get_best_index: (a: number) => number;
export const world_get_best_score: (a: number) => number;
export const world_get_generation: (a: number) => number;
export const world_get_obstacle_count: (a: number) => number;
export const world_get_obstacle_x: (a: number, b: number) => number;
export const world_get_fitness_history: (a: number) => [number, number];
export const world_get_score_of: (a: number, b: number) => number;
export const world_get_best_input_weights: (a: number) => [number, number];
export const world_get_best_output_weights: (a: number) => [number, number];
export const world_get_best_bias: (a: number) => number;
export const world_set_best_weights: (a: number, b: number, c: number) => void;
export const world_set_best_bias: (a: number, b: number) => void;
export const world_count_alive: (a: number) => number;
export const world_get_average_score: (a: number) => number;
export const world_is_alive: (a: number, b: number) => number;
export const world_get_population_size: (a: number) => number;
export const world_get_dino_x: (a: number, b: number) => number;
export const world_get_dino_y: (a: number, b: number) => number;
export const world_get_speed_multiplier: (a: number) => number;
export const __wbindgen_export_0: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_start: () => void;
